project:
  type: website
  output-dir: docs
  
website: 
  title: "The La Selva-Barva MetaNetwork"
  site-url: https://laselva-metanetwork.github.io
  navbar:
    left: 
      - href: index.qmd
        text: Home
      - href: species.qmd
        text: Species
        
format:
  html:
    theme:
      - lux
      
      