project:
  type: website
  output-dir: docs
  
website: 
  title: "The La Selva-Barva MetaNetwork"
  site-url: https://space-lab-msu.github.io/LaSelva-MetaNetwork/
  navbar:
    left: 
      - href: index.qmd
        text: Home
      - text: "Species"
        menu:
        - href: species/plants/index.qmd
          text: "Plants"
        
format:
  html:
    theme:
      - lux
      
      